### ISSUE TITLE
Resize issue with scipy

### ISSUE THREAD

**Issue by Bhirpara** [ptirupat/AnomalyDetection_CVPR18#15]
C:\Users\bhirpara\Downloads\AnomalyDetection_CVPR18-master>python demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from c3d import *
  File "C:\Users\bhirpara\Downloads\AnomalyDetection_CVPR18-master\c3d.py", line 22, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (C:\Software\Python\lib\site-packages\scipy\misc\__init__.py)

**Comment by kuanhungchen** [comment]
@Bhirpara
You can solve it by installing PIL (ex: `pip install pillow`)

**Comment by sonal-511** [comment]
pip install scipy==1.1.0 and pip install pillow resolves the issue
