### ISSUE TITLE
TypeError: 'MovieWriterRegistry' object is not an iterator

### ISSUE THREAD

**Issue by smahesh29** [ptirupat/AnomalyDetection_CVPR18#18]
Traceback (most recent call last):
  File "demo.py", line 53, in <module>
    run_demo()
  File "demo.py", line 49, in run_demo
    visualize_predictions(cfg.sample_video_path, predictions, save_path)
  File "C:\Users\Mahesh Sawant\Desktop\New folder\AnomalyDetection_CVPR18-master\utils\visualization_util.py", line 57, in visualize_predictions
    anim.save(save_path, dpi=200, writer='imagemagick')
  File "C:\Users\Mahesh Sawant\Desktop\New folder\my_project\lib\site-packages\matplotlib\animation.py", line 1102, in save
    alt_writer = next(writers, None)
TypeError: 'MovieWriterRegistry' object is not an iterator

**Comment by dexXxed** [comment]
Hello! 
I had the same issue, I have remade some code from this repo and it is located [here](https://github.com/dexXxed/abnormal-event-detection)

You can test it and if you have some issues, you can make it on my repo!
