### ISSUE TITLE
problem while running sudo python extract_C3D_feature.py

### ISSUE THREAD

**Issue by cervantes-loves-ai** [ptirupat/AnomalyDetection_CVPR18#19]
sh c3d_sport1m_feature_extraction_frm.sh  runs perfectly but while run sudo python extract_C3D_feature.py i faced this problem

sudo python extract_C3D_feature.py 
Traceback (most recent call last):
  File "extract_C3D_feature.py", line 7, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/usr/local/lib/python2.7/dist-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

even though i reinstall numpy sevaral times but still have same error. also when i run  with python3 i saw this error

sudo python3 extract_C3D_feature.py 
  File "extract_C3D_feature.py", line 32
    print "[Info] trained_model={} found. Good to go!".format(trained_model)
                                                     ^
SyntaxError: invalid syntax

thanks in advance

**Comment by dexXxed** [comment]
Hello!
I have fixed this issue, working code is [here](https://github.com/dexXxed/abnormal-event-detection)
