### ISSUE TITLE
how can i get the c3d_mean.npy

### ISSUE THREAD

**Issue by lz28lz28** [ptirupat/AnomalyDetection_CVPR18#2]
hi, thank you for your codes
but,how can i get the c3d_mean.npy .
when i run demo.py ,i get the error like this :

Downloading data from https://github.com/adamcasson/c3d/releases/download/v0.1/c3d_mean.npy
Traceback (most recent call last):
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/usercsy/anaconda3/envs/tf-gpu2/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

waiting for your replay

**Comment by ptirupat** [comment]
I am not sure how to fix the SSL issue, but you could open the link in your browser and save the c3d_mean.npy to the disk and use that location in line 21 of c3d.py.
